### ISSUE TITLE
[IMPROVEMENT] Need better default image

### ISSUE THREAD

**Issue by grevicoc** [KATITB22/announcement-lms-FE#65]
![image](https://user-images.githubusercontent.com/60306167/184161994-db7fe297-7745-4e7a-bc90-de7a35f2619d.png)

currently our default image (if feature image broken) is our logo

**Comment by IloveNooodles** [comment]
INI GIMANA YAKK GESYAKKK BLOM

**Comment by IloveNooodles** [comment]
done ya
